INSERT INTO `automovil`(`marca_id`, `cambio_id`, `combustible_id`, `estado_id`, `modelo`, `precio`, `anio`, `kilometraje`, `color`, `plazas`, `puertas`, `descripcion`) VALUES 
(1,1,1,1,"A2 1.6 FSi 110cv",2999,2003,180000,"Gris plata",5,5,"VENDIDO 
EN MUY BUEN ESTADO, llantas de aleación, elevalunas y espejos eléctricos, climatizador, ordenador de abordo, ASR, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio EUR 120 por cambio de nombre."),
(2,1,2,1,"407 1.6 HDi ST CONFORT 110cv VENDIDO",3000,2005,185000,"GRIS PLOMO",5,5,"VENDIDO 
COCHE EN MUY BUEN ESTADO, pintura metalizada, elevalunas eléctricos, espejos exteriores eléctricos, climatizador, bluettoth, ordenador de abordo, velocidad de crucero, faros antiniebla, llantas de aleación, sensor de luz y lluvia. cristales tintados. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio EUR 120 por cambio de nombre. Color Gris plomo"),
(3,1,2,1,"FREELANDER 2 TD4-S 4X4 160cv",9600,2007,120000,"NEGRO",5,5,"(VENDIDO)EN MUY BUEN ESTADO, UNICO PROPIETARIO, dos llaves inteligentes, climatizador, ordenador de abordo, pantalla doble dim tactil alpine, control de estabilidad, mando seleccion de traccion, 4 elevalunas electricos, llantas aleacion 17 , lavafaros, velocidad de crucero, mandos al volante, espejos electricos y abatibles, etc precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre."),
(4,1,2,1,"C4 HDI 2. 0 EXCLUSIVE 136cv",4200,2005,152000,"AZUL",5,5,"(RESERVADO)COCHE EN MUY BUEN ESTADO. ITV 2019, ordenador de abordo, volante multifunción, manos libres blueetoth, climatizador bizona, navegador, Radio CD con cargador de CD, conexiones Jack para aparatos externos, elevalunas eléctricos, retrovisores eléctricos con intermitentes incorporados, 6 velocidades, asientos calefactables, sensores de aparcamiento, sensor de luz y lluvia, repozabrazos, llantas de aleación. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 mesesde garantía. Hay que sumarle al precio EUR 120 por cambio de nombre."),
(4,1,2,1,"XSARA PICASSO 1.6 HDI 90cv",3800,2007,145000,"GRIS PLOMO",5,5,"EN PERFECTO ESTADO, unico propietario dos llabes, climatizador, sensor luz y llubia, mandos al volante, velocidad de crucero, ordenador de abordo, cierre centralizado con mando, espejos electricos, llantas de aleacion, cristales ahumados, apoyabrazos, 4 elevalunas etc. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre"),
(5,1,1,1,"FOCUS 1.6 TITANIUM 100cv",3500,2006,170000,"ROJO",3,5,"VENDIDO 
EN MUY BUEN ESTADO. Llantas de aleación de 18 , volante de cuero, elevalunas y espejos eléctricos, ordenador de abordo, climatizador. Mandos al volante, sensor de luz y lluvia, apoyabrazos, radio CD Sony, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio EUR 120 por cambio de nombre."),
(2,1,2,3,"308 1.6 VTi 120cv",4700,2007,151000,"GRANATE",5,5,"EN MUY BUEN ESTADO. Premium. Climatizador, 4 elevalunas eléctricos y retrovisores eléctricos. Sujeciones ISOFIX, ordenador de abordo, velocidad de crucero y limitador, apoyabrazos, llantas de aleación. Techo panorámico y acabados SPORT, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio EUR 120 por cambio de nombre."),
(2,1,1,1,"308 1.6 VTi 120cv",4999,2007,95000,"AZUL",5,5,"EN MUY BUEN ESTADO, motor de cadena, climatizador bizona, elevalunas eléctricos, espejos eléctricos, llantas de aleación, volante con mandos, cierre centralizado, faros antiniebla, acabado sport, anclajes ISOFIX delante y detrás, asientos traseros partidos, con detalles cromados. Velocidad de crucero y limitador. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio EUR 120 por cambio de nombre."),
(5,1,2,3,"FIESTA 1.4 TDCi 70cv",4500,2009,120000,"BEIGE",5,5,"BUEN ESTADO. Un único propietario. Llantas de aleación, elevalunas eléctrico, retrovisores eléctricos, climatizador, ordenador de abordo. Cierre centralizado con mando. Entrada auxiliar MP3, sujeciones ISOFIX, faros antiniebla, color beige, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio 120€ por cambio de nombre"),
(2,1,2,1,"206 2.0 HDi 90cv",2600,2004,160000,"GRIS",5,5,"EN BUEN ESTADO, Dos llaves, techo panoramico, llantas de aleacion, elevalunas electricos, cierre centralizado con mando, ordenador de abordo, sensor de luces, bola de remolque, climatizador, espejos electricos etc. Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre."),
(2,1,2,2,"1007 1.4 HDi 70cv",3500,2008,140000,"GRIS PLATA",3,5,"COCHE EN MUY BUEN ESTADO, ordenador de abordo, 2 puertas laterales correderas eléctricas, elevalunas eléctricos, manos libres, cierre centralizado, pintura metalizada, ESP, aire acondicionado, asientos traseros abatibles, 2 llaves, cristales ahumados, llantas de aleación, Radio CD con MP3, faros antiniebla, sujeciones ISOFIX, sensor de aparcamiento. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle el precio EUR 120 por cambiode nombre"),
(4,1,1,1,"C4 1.6",4200,2006,82000,"GRIS PLOMO",5,5,"EN MUY BUEN ESTADO. Mandos al volante, llantas de aleación de 17 , sensores de luz y lluvia, velocidad de crucero, limitador, climatizador bizona, ordenador de abordo, cuatro elevalunas eléctricos y espejos eléctricos, cierre con mando, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio EUR 120 por cambio de nombre"),
(2,1,1,1,"308 1.4 SP CONFORT 98cv",5999,2010,87000,"GRANATE",5,5,"VENDIDO
EN MUY BUEN ESTADO. Llantas de aleación, ordenador de abordo, 4 elevalunas eléctricos. Radio CD, espejos retrovisores eléctricos, climatizador, apoyabrazos, etc. Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio 120 € por cambio de nombre."),
(5,1,2,1,"FOCUS C-MAX 1.8 TDCi",3999,2007,143000,"AZUL CIELO",5,5,"EN MUY BUEN ESTADO. Elevalunas y espejos eléctricos, ordenador de abordo, apoyabrazos, velocidad de crucero con mando en el volante, climatizador bizona, cristales ahumados de origen, radio CD, guantera con luz, llantas de aleación, 2 llaves, sujeciones isofix, cierre centralizado, cortinillas traseras, libro de revisiones del servicio oficial, etc. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120,-- por cambio de nombre."),
(6,1,1,2,"POLO 1.4 75cv",2800,2004,110000,"NEGRO",5,5,"RESERVADO EN MUY BUEN ESTADO. 2 llaves, aire acondicionado, elevalunas y espejos eléctricos. Radio CD con entrada USB y altavoces de 120w, etc. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre."),
(4,1,2,1,"C4 PICASSO 1.6 HDi EXCLUSIVE 110 cv",5500,2007,114000,"PLATA",5,5,"VENDIDO 
EN MUY BUEN ESTADO. 4 elevalunas eléctricos, espejos plegables y eléctricos, ordenador de abordo, navegador, velocidad de crucero, climatizador bizona, controles en el volante, apoyabrazos, sujeciones isofix, radio CD con MP3, llantas de aleación, sensor de aparcamiento, sensor de luz y lluvia. Luces Xenon, suspensión neumática trasera, freno de mano eléctrico, techo panorámico, cristales ahumados, llantas de 18 , cortinillas, asientos anchos, etc. Precio y equipación salvo error tipográfico. Se entrega elvehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre."),
(5,1,2,1,"GALAXY 2.0 TDCi GHIA 140cv",5500,2007,240000,"AZUL CIELO",5,7,"EN MUY BUEN ESTADO. Llantas de aleación, 7 plazas, 6 velocidades, climatizador bizona, sensor de aparcamiento, sensor de luz y lluvia, techo panorámico, volante de piel y asientos de cuero, 4 elevalunas eléctricos y espejos eléctricos, manos libres, apoyabrazos, control de tracción, velocidad de crucero y limitador, freno de mano eléctrico, etc. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre."),
(2,1,2,1,"PARTNER TEPEE OUTDOOR 1.6 HDI 92cv",7200,2010,130000,"BEIGE",5,5,"(RESERVADA)EN MUY BUEN ESTADO. único propietario, 2 llaves, doble puerta lateral, llantas de aleación, climatizador bizona, bola de remolque, ordenador de abordo, velocidad de crucero y limitador, espejos y elevalunas eléctricos, porta esquies, cristales traseros abatibles, todas las revisiones en servicio oficial, etc. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre. ¡Visite nuestra web!www. automovileslucentum. com."),
(7,1,2,1,"ZAFIRA 1. 9 CDTI ENJOY 120cv",5400,2008,120000,"NEGRO",5,7,"EN MUY BUEN ESTADO. Único propietario, 2 llaves, 6 velocidades, climatizador, mandos al volante, 7 plazas, velocidad de crucero, espejos y elevalunas eléctricos, llantas de aleación, etc. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre."),
(6,1,2,2,"GOLF IV 1.9TDI 110cv",1800,2001,216000,"NEGRO",3,5,"EN MUY BUEN ESTADO. Llantas de aleación de 18 , bola de remolque, elevalunas eléctricos, radio CD, control de estabilidad, ordenador de abordo, climatizador, cierre centralizado, etc. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 6 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre."),
(5,1,2,1,"FOCUS 1.6 TDCi 90 cv",3400,2006,155000,"GRANATE",5,5,"EN MUY BUEN ESTADO. 2 llaves, climatizador bizona, espejos y elevalunas eléctricos, radio CD, volante de cuero, ordenador de abordo, limitador y velocidad de crucero, mandos en el volante, etc. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre."),
(8,1,2,1,"DOBLÓ 1.6 JTD 105cv",6999,2012,115000,"GRIS PLATA",5,5,"EN MUY BUEN ESTADO, 2 llaves, sujeciones ISOFIX, llantas de aleación, elevalunas eléctricos, velocidad de crucero, mandos en el volante, ordenador de abordo, radio CD, aire acondicionado, 6 velocidades, dirección asistida, bluetooth manos libres Parrot, apoyabrazos, etc. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre."),
(2,1,1,1,"308 1.6 VTi 120cv",5500,2007,94000,"GRIS PLOMO",5,5,"VENDIDO 
 En muy buen estado. premium. climatizador, 4 elevalunas eléctricos y retrovisores eléctricos. sujeciones isofix, ordenador de abordo, velocidad de crucero y limitador, apoyabrazos, llantas de aleación. techo panorámico y acabados sport, etc. precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre."),
(9,1,1,1,"CLIO 0.9 TCe 90cv",7999,2015,60000,"BLANCO",5,5,"En perfecto estado. Un único dueño, elevalunas eléctricos, espejos eléctricos con intermitentes, ordenador de abordo, llantas de aleación de 17 , velocidad de crucero, navegador con pantalla táctil, luces automáticas, sensor de aparcamiento trasero y cámara de marcha atrás, sensor de luz y lluvia, luces LED diurnas, sonido BASS REFLEX, etc. Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre."),
(10,1,2,2,"ALTEA STYLANCE 1.9TDi 105cv",4500,2005,135000,"ORO",5,5,"Un único dueño, 2 llaves, llantas de aleación, mandos al volante, velocidad de crucero, control de estabilidad, climatizador, ordenador de abordo, apoyabrazos, espejos eléctricos y plegables, 4 elevalunas eléctricos, sujeciones ISOFIX, etc."),
(11,1,1,2,"A150 95cv",4800,2006,120000,"VERDE METALIZADO",3,5,"Un único dueño, en muy buen estado, espejos y elevalunas eléctricos, radio CD con entrada USB, ordenador de abordo, climatizador, sujeciones ISOFIX, bajo consumo, etc. Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre."),
(12,1,2,1,"CARNIVAL 2.9D RS",2400,2001,100000,"AZUL MARINO",5,6,"En muy buen estado, 2 llaves, 2 puertas laterales, 6 plazas, elevalunas eléctricos, asientos con apoya brazos, radio CD con entrada USB, aire acondicionado, dirección asistida, etc. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre."),
(5,1,1,2,"FOCUS 1.6 100 cv",4200,2006,100000,"AZUL METALIZADO",5,5,"Un único dueño, en muy buen estado. 2 llaves, llantas de aleación, elevalunas y espejos eléctricos, volante de cuero, ordenador de abordo, velocidad de crucero y limitador con mandos en el volante, climatizador bizona, radio CD, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(13,1,2,2,"320d 160cv",5999,2006,230000,"NEGRO",4,5,"En muy buen estado, llantas de 17 , asientos de piel beige, 4 elevalunas y espejos eléctricos, navegador profesional, ordenador de abordo, sensores de aparcamiento, luz y lluvia, apoya brazos, climatizador bizona, radio cd, control de tracción, mandos en el volante, asientos calefactables, equipo multimedia, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(5,1,1,1,"FOCUS C-MAX 1.6 110cv",2999,2005,175000,"AZUL MARINO",5,5,"En muy buen estado, 2 llaves, elevalunas y espejos eléctricos, volante de cuero, ordenador de abordo, mandos al volante, radio CD, aire acondicionado, velocidad de crucero y limitador, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(4,1,1,3,"C4 1.4 COLLECTION 90 cv",3999,2006,90000,"NEGRO",5,5,"(RESERVADO)En muy buen estado, llantas de aleación, 2 llaves, 4 elevalunas y espejos eléctricos, ordenador de abordo, velocidad de crucero y limitador con mandos en el volante, climatizador bizona, sensor de luz y lluvia, espejos antideslumbrantes, radio CD, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay quesumarle al precio eur 120 por cambio de nombre."),
(14,2,1,1,"FORTWO COUPÉ 1.0 70 cv",5500,2011,35000,"GRIS MATE",3,2,"En muy buen estado, un único dueño, elevalunas eléctricos, 2 llaves, pantalla multimedia táctil con navegador y entrada USB, aire acondicionado, techo panorámico, llantas de aleación, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay quesumarle al precio eur 120 por cambio de nombre."),
(6,2,2,3,"GOLF 1.9 TDi 105cv",5500,2006,170000,"AZUL MARINO",5,5,"En muy buen estado, llantas de aleación, cambio automático DSG, climatizador bizona, 4 elevalunas y espejos eléctricos, ESP antiderrape, manos libres bluetooth, ordenador de abordo, apoya brazos, sujeciones ISOFIX, mantenimiento al día, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay quesumarle al precio eur 120 por cambio de nombre."),
(10,1,2,1,"IBIZA 1.9 TDi 100cv",3000,2003,185000,"NEGRO",5,5,"VENDIDO 
En muy buen estado, un único dueño, 2 llaves, llantas de aleación, elevalunas y espejos eléctricos, radio CD con entrada USB, climatizador, volante de cuero, dirección asistida, faros antiniebla, acabado sport, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay quesumarle al precio eur 120 por cambio de nombre."),
(15,1,2,1,"ACCORD 2.2 i-CDTi 140cv",5999,2006,160000,"GRIS PLOMO",4,5,"Un único dueño, llantas de aleación, techo solar, asientos de piel eléctricos y calefactables, volante de piel, 4 elevalunas y espejos eléctricos abatibles, 6 velocidades, ordenador de abordo, velocidad de crucero y limitador con mandos en el volante, apoya brazos, climatizador bizona, faros de xenon, radio CD con cargador de 6 CD, cortinillas traseras, retrovisor antideslumbrante, sensor de luz y lluvia, etc. Precio y equipamiento válido salvo error tipográfico.Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(10,1,1,3,"ALTEA 1.6 102cv",4200,2004,65000,"AZUL METALIZADO",5,5,"Un único dueño, en muy buen estado, ordenador de abordo, radio CD con mandos en el volante, bajo consumo, 4 elevalunas y espejos eléctricos y abatibles, llantas de aleación, climatizador, sujeciones isofix, control de tracción, apoya brazos, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(11,2,2,3,"C220 CDI 150 cv",5500,2004,170000,"BEIGE METALIZADO",3,5,"VENDIDO En muy buen estado, dos llaves, llantas de aleación, asientos de piel, volante de cuero, elevalunas y espejos eléctricos, ordenador de a bordo, velocidad de crucero y limitador con mandos en el volante, climatizador bizona, sensor de luz y lluvia, pantalla multimedia con navegador, manos libres bluetooth Parrot, apoya brazos, radio cd con entrada USB, faros antiniebla, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía.Hay que sumarle al precio eur 120 por cambio de nombre."),
(1,2,2,1,"A4 2.0 TDi 140 cv S-LINE",7500,2007,165000,"NEGRO",4,5,"En perfecto estado, un único dueño, dos llaves, volante multifunción, climatizador bizona, ordenador de a bordo, 4 elevalunas y espejos plegables elécricos, alarma, faros bixenon, llantas de 18 , acabado S-Line interior y exterior, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(10,1,1,1,"IBIZA SPORT RIDER 70 cv",4500,2008,80000,"NEGRO",5,5,"VENDIDO 
Seat Ibiza, llantas de aleación, climatizador, volante multifunción, velocidad de crucero, 5 puertas, faros antinieblas, elevalunas eléctricos, faros antinieblas, cierre centralizado con mando a distancia, 2 llaves, motor por cadena de distribución etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(11,1,1,1,"C180 KOMPRESSOR 140 cv",7600,2007,90000,"AZUL MARINO",4,5,"VENDIDO ESTADO IMPOLUTO, dos llaves, faros de xenon, velocidad de crucero y limitador, sensor de luz y lluvia, llantas 17 doble medida con neumaticos continental recien puestos, cambio manual de 6 velocidades, volante de cuero con mandos multifunción, retrovisores electricos, climatizador bizona, apoya brazos central, control de tracción, sensores de aparcamiento traseros, pantalla de dvd en el techo, acabado sportedition, Precio y equipamiento válido salvo error tipográfico.Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(16,1,2,3,"AVENSIS",4500,2010,270000,"GRIS PLOMO",4,5,"Toyota Avensis, motor 2. 0 volante multifunción, llantas de aleacion, climatizador bizona, 4 elevalunas electricos, freno de mano electrico, cambio manual de 6 velocidades, 2 llaves, sensor de luz y lluvia, Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 mesesde garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(12,1,2,2,"SORENTO 2.5 CRDI EX",4999,2005,180000,"NEGRO",5,5,"VENDIDO En muy buen estado, 2 llaves, 4 elevalunas y espejos eléctricos, apoya brazos, climatizador, pantalla DVD en el techo, radio CD, manos libres, sujeciones isofix, bola de remolque, 4X4, etc. Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(9,1,2,1,"SCENIC 1.9 DCI 120cv",3500,2004,115000,"NEGRO",5,5,"En muy buen estado, 4 elevalunas y espejos eléctricos, 6 velocidades, climatizador, radio cd con bluetooth y entrada usb, ordenador de abordo, velocidad de crucero y limitador con mandos en el volante, apoya brazos, techo panorámico, freno de mano eléctrico, sujeciones isofix, llantas de aleación, cortinillas traseras, sensor de luz y lluvia, asientos mixtos de piel y tela, tarjeta inteligente uso a distancia, acabado de luxe Privilege, etc. Precio y equipamientoválido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay quesumarle al precio eur 120 por cambio de nombre."),
(17,1,2,3,"RENEGADE 1.6 LONGITUDE 120 cv",15500,2015,44000,"ROJO",5,5,"En muy buen estado, 2 llaves, llantas de aleación, bola de remolque, 4 elevalunas y espejos eléctricos, asientos con lumbar eléctricos, pantalla multimedia táctil con entrada USB, volante de cuero con mandos, apoya brazos, sujeciones isofix, ordenador de abordo, 6 velocidades, freno de mano eléctrico, control de tracción, luces diurnas, sensor de aparcamiento delantero y trasero, velocidad de crucero y limitador, start + stop, etc. Precio y equipamiento válidosalvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre."),
(6,1,2,1,"PASSAT 1.9 TDI 130 CV",2700,2003,280000,"GRIS PLOMO",4,5,"(VEHICULO DISPONIBLE)Passat 1. 9 tdi 130cv cuenta con climatizador, radio cd, elevalunas electricos, cierre centralizado con mando a distancia, llantas de aleacion etc muy buen estado. precio y equipación salvo error tipográfico. se entrega el vehículo con 12 meses de garantía. al precio hay que sumarle eur 120, -- por cambio de nombre. ¡visite nuestra web www. automovileslucentum. com. Color gris plomo"),
(4,1,2,3,"C4 1.6 HDI 90 CV",3600,2006,170000,"AZUL CIELO",5,5,"BIEN CUIDADO, cierre centralizado, ordenador de abordo, espejos electricos, sensor de luz y llubia, 4 elevalunas electricos, climatizador bi-zona, velocidad de crucero, mandos al volante, llantas de aleacion, radio cd con mando, etc, Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, -- por cambio de nombre. ¡Visite nuestra web!www. automovileslucentum."),
(9,1,1,1,"SCENIC 1.6 16V",3300,2005,70000,"NEGRO",5,5,"VENDIDO
MUY CUIDADO, unico propietario, climatizador, sensor luz y lluvia, velocidad de crucero, 4 elevalunas electricos, cierre centralizado, ordenador de abordo, mandos en el volante, freno de mano electrico, llantas de aleacion, isofix, Precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay quesumarle al precio eur 120 por cambio de nombre. Visite nuestra web! www. automovileslucentum. com."),
(11,1,1,2,"CLK 200 KOMPRESSOR",5999,2003,85000,"AZUL MARINO",2,4,"VEHICULO EN EXCELENTE ESTADO,AVANTGARDE,CLIMATIZADOR,CONTROL DE VELOCIDAD,ORDENADOR DE ABORDO,TAPICERIA DE CUERO,6 VELOCIDADES,LLANTA DE ALEACION,UN SOLO DUEÑO,LISTO PARA CIRCULAR,VOLANTE DE CUERO CON MANDOS,SENSOR DE LUZ Y LLUVIA,ESPEJOS ELECTRICOS,ETC ETC. precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre.caduca en 59 dias. visite nuestra web! www. automovileslucentum. com"),
(10,1,1,1,"IBIZA 1.4",6500,2012,40000,"ROJO",5,5,"COMO NUEVO, UNICO PROPIETARIO, DOS LLAVES,85CV, climatizador, radio cd mp3 entrada auxiliar, velocidad de crucero, mandos al volante, ordenador de abordo, espejos electricos, elevalunas electricos, llantas de aleacion, faros antiniebla, precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. color granate caduca en 59 dias. visite nuestra web! www. automovileslucentum. com."),
(2,1,1,3,"308 SW 1.6 VTi 120cv",4999,2008,90000,"GRIS PLATA",5,5,"VENDIDO VEHICULO PROCEDENTE DE UN SOLO PROPIETARIO,Llantas de Aleación,Climatizador bi zona,Velocidad de Crucero y Limitador,Techo Panoramico,Radio CD con mandos al volante,elevalunas electrico,anclaje ISOFIX silla niños,Cristales traseros ahumados de serie,bajo consumo,Excelente estado. Precio y equipación salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle EUR 120, - por cambio de nombre. Visite nuestra web! www. automovileslucentum.com"),
(4,1,2,1,"C4 PICASSO 1.6 HDI 110CV 6V",8500,2013,110000,"GRIS PLOMO",5,5,"VENDIDO 
en execelente estado, unico propietario, dos llaves, velocidad de crucero y limitador, sensor de luz y lluvia, apoyabrazos, volante de cuero con mandos, 4 elevalunas electricos, llantas de aleacion, cristales ahumados, climatizador por zonas, luces diurnas, isofixfreno estacionamiento electrico, radio cd mp3 entradas aux, etc precio y equipación salvo error tipográfico. se entrega el vehículo con 12 meses de garantía. al precio hay que sumarleeur 120, -- por cambio de nombre.¡visite nuestra web! www. automovileslucentum. com. we speak english"),
(4,1,2,1,"BERLINGO 1.6 HDI",4999,2007,55000,"AZUL CIELO",5,5,"(vehiculo disponible)como nueva un solo propietario, doble puerta lateral, espejo electrico, aire acondicionado, cienrre centralizado, apoyabrazos, ordenador de abordo, elevalunas electricos, mandos al volante, etc precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. visite nuestra web! www. automovileslucentum. com."),
(10,1,2,1,"ALTEA",6900,2011,90000,"Beige",5,5,"(vehiculo disponible)muy cuidado un unico propietario, dos llaves, cierre centralizado con mando, climatizador bi-zona, 4 elevalunas electricos, control de traccion, velocidad de crucero, volante de cuero con mandos, cristales ahumados, llantas de aleacion, espejos electricos y abatibles, ordenador de abordo, isofix, control presion de neumaticos etc, , etc precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio denombre visite nuestra web! www. automovileslucentum. com."),
(13,1,2,2,"320 D 6V",9499,2007,120000,"GRIS PLATA",4,5,"(RESERVADO)MUY CUIDADO, dos llaves, aranque con boton, asientos piel negra, techo solar, 4 elevalunas electricos, llantas M en 19 con neumaticos al 90%, navegador profesional(pantalla grande)sensor de luz y lluvia,sensores de aparcamiento,ordenador de abordo, volante de piel con mandos, asientos calefactables, cortinilla trasera electrica, manos libres, apoyabrazos, espejos electricos, etc. precio y equipación salvo error tipográfico. se entrega el vehículo con 12 meses de garantía. al precio hay que sumarleeur 120, -- por cambio de nombre. visite nuestra web! www. automovileslucentum. com."),
(13,1,2,3,"207 1.4 hdi sport",4800,2010,100000,"NEGRO",5,5,"(vehiculo disponible)buen estado, unico propietario, dos llaves, aire acondicionado, llantas de aleacion. espejos electricos, cierre centralizado con mando, ordenador de abordo, elevalunas electricos, radio cd mp3, mandos en el volante etc precio y equipación salvo error tipográfico. se entrega el vehículo con 12 meses de garantía. al precio hay que sumarle eur 120, -- por cambio de nombre. visite nuestra web! www. automovileslucentum. com."),
(6,1,2,1,"POLO",5499,2010,160000,"Blanco",3,5,"(VENDIDO)unico propietario buen estado mecanico y carroceria, dos llaves, aire acondicionado, cierre centralizado con mando, elevalunas electricos, espejos electricos, ordenador de abordo, control de estabilidad etc etc precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. visite nuestra web! www. automovileslucentum. com."),
(2,1,2,1,"PARTNER 1.9 ATMOSFÉRICO",2800,1998,50000,"AZUL MARINO",3,5,"Peugeot Partner 1.9 atmosférico. !!!!!50.000 MIL KM!!!!Vehículo super cuidado, único propietario, aire acondicionado, kilometraje real certificado, 5 plazas, ventanas abatibles, etc precio y equipamiento válido salvo error tipográfico. Se entrega con 12 meses de garantía. Hay que sumarle al precio eur 120 por cambio de nombre. visite nuestra web! www. automovileslucentum. com."),
(18,1,1,1,"SWIFT",3800,2007,120000,"GRIS PLATA",5,5,"Suzuki SWIFT 1.3 90CV. Vehículo disponible 
 Único propietario, dos llaves. Aire acondicionado, cierre centralizado, cristales ahumados, elevalunas eléctricos, retrovisores eléctricos, ordenador de abordo, radio cd, dirección asistida, etc... Precio y equipación correcto salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle eur 120, #por cambio de nombre# ¡Visite nuestra web! www. automovileslucentum. com."),
(5,1,2,3,"FOCUS 1.8 TDCI",2600,2003,130000,"GRIS PLATA",3,5,"Ford Focus 1.8 tdci (MOTOR FORD). Vehículo disponible. Muy buen estado. Aire acondicionado, radio cd, elevalunas eléctricos,cierre centralizado con mando a distancia,llantas de aleación, dos llaves, faros antiniebla, acabado sport, etc... precio y equipación correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www. automovileslucentum. com."),
(6,1,1,1,"GOLF V GT 1.6",5500,2007,138000,"NEGRO",3,5,"Volkswagen Golf V GT 1.6 105cv. VENDIDO
 Estado impecable, un único propietario, 2 llaves, faros de xennon, ordenador de a bordo, climatizador, retrovisores eléctricos calefactables, sensor de lluvia y luminosidad, radio CD, ESP desconectable, llantas de aleación, neumáticos de primeras marcas, etc...precio y equipación correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www. automovileslucentum. com."),
(10,1,1,3,"IBIZA SPORT RIDER",3600,2006,135000,"ROJO",5,5,"Seat Ibiza sport 1.4. VEHÍCULO DISPONIBLE
 En mi buen estado, único dueño. Llantas de aleación, Climatizador, elevalunas eléctricos, mando a distancia, mandos en el volante, Radio CD MP·, etc...precio y equipación correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www. automovileslucentum. com."),
(16,1,2,1,"Corolla Verso 2.2 D4D 177cv Sport",4800,2007,200000,"GRIS PLATA",5,7,"Toyota Corolla Verso D4D D-CAT 2.2 177cv Sport (7 plazas) (VEHÍCULO DISPONIBLE)
 En muy buen estado, 7 plazas, motor de cadena, muy equipado: llantas de aleación de 17 , 3 llaves, start&stop, 6 marchas, espejos y elevalunas eléctricos, mandos en el volante, climatizador bi-zona, radio cd, control de velocidad, control de tracción, función manos libres, anclajes isofix en plazas traseras, airbag conductor/pasajero, 2 apoyabrazos delanteros, barras de techo, etc... precio y equipación correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www. automovileslucentum. com."),
(8,1,2,1,"DOBLÓ 1.9 D COMBI",3000,2004,170000,"GRIS PLATA",4,5,"VEHÍCULO DISPONIBLE.
 En buen estado, aire acondicionado, radio, elevalunas eléctricos delanteros, ventanillas traseras abatibles, portón lateral derecho deslizante, doble portón trasero apertura 180º, pintura metalizada gris plata, etc...precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#."),
(2,1,1,3,"207 1.4 75cv THP URBAN",4200,2007,100000,"NEGRO",5,5,"VEHÍCULO DISPONIBLE
 En muy buen estado, un único dueño, dos llaves. Llantas de aleación, elevalunas y espejos eléctricos, aire acondicionado, radio CD con mandos en el volante, Pomo palanca de cambios de aluminio, Volante de Cuero, antena aleta de tiburón, acabado sport, etc...precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www. automovileslucentum. com."),
(2,1,2,1,"207 1.4 HDI BLINE",5500,2011,95000,"GRIS PLOMO",5,5,"VENDIDO 
Muy buen estado, único propietario, dos llaves, Radio CD, aire acondicionado, elevalunas eléctricos, retrovisores eléctricos, etc...precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www. automovileslucentum. com."),
(7,1,1,3,"CORSA 1.4 TWINPORT 16V 90CV",2999,2006,108000,"NEGRO",3,5,"En muy buen estado, dos llaves, llantas de aleación, elevalunas eléctricos, ordenador de a bordo, radio cd con mandos en el volante, tapicería de tela, volante de cuero, faros antiniebla delanteros, airbags delanteros, transmisión de cadena, etc...precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#."),
(2,1,2,1,"307 2.0 hdi 16v",3200,2005,120000,"ROJO",5,5,"VENDIDO 
 En muy buen estado, único propietario, dos llaves, elevalunas eléctricos, climatizador, Radio CD con mandos en el volante, palanca de cuero, ordenador de a bordo, Airbags delanteros (el del pasajero desconectable), airbags laterales delanteros, cierre centralizado, etc... precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com"),
(5,1,2,1,"FIESTA TITANIUM 1.6 TDCI",4999,2010,150000,"BLANCO",5,5,"VEHÍCULO VENDIDO 
Estado impecable, un solo propietario, dos llaves, llantas de aleación 16 , radio cd con mandos en el volante, ordenador de a bordo, volante de cuero, climatizador, 4 elevalunas eléctricos, manos libres, retrovisores eléctricos, cierre centralizado con mando a distancia, llave inalámbrica, entrada usb, airbags delanteros, sensor de lluvia y luminosidad, faros antiniebla, etc... precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com"),
(2,1,1,3,"207 1.4 75CV",4200,2007,145000,"GRIS PLATA",5,5,"VEHÍCULO DISPONIBLE. En muy buen estado, un único propietario, dos llaves, elevalunas eléctricos, cierre centralizado, retrovisores eléctricos, aire acondicionado, radio CD con mandos en el volante, anclajes isofix en plazas traseras, itv vigente hasta 2020, etc... Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre.
 visite nuestra web! www.automovileslucentum.com"),
(5,1,2,3,"KUGA 2.0 TDCI TITANIUM 4WD",9500,2009,125000,"GRIS PLATA",5,5,"VEHÍCULO DISPONIBLE
 En perfecto estado, único propietario, dos llaves inalámbricas, llantas de aleación 17 , faros antiniebla delanteros, retrovisores eléctricos, velocidad de crucero, limitador de velocidad, navegador con radio cd y SD card con mandos en el volante, climatizador bizona, manos libres, sensor de lluvia y luminosidad, sensores de aparcamiento delanteros y traseros, airbags delanteros/laterales, apoyabrazos central con compartimento organizador, 4 elevalunas eléctricos, asiento y volante regulable, anclajes isofix en plazas traseras, función 4wd con 6 marchas, motor FORD, etc... Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre.
 visite nuestra web! www.automovileslucentum.com"),
(1,1,2,3,"A3 AMBITION 1.9 TDI 105CV",5600,2006,190000,"NEGRO",3,5,"VEHÍCULO DISPONIBLE
En buen estado, único propietario, llantas de aleación 17, velocidad de crucero, faros antiniebla, Radio CD, Climatizador bizona, luneta trasera calefactable, asiento conductor regulable, volante de cuero, airbags laterales delanteros, elevalunas eléctricos, retrovisores eléctricos, etc... Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre.
visite nuestra web! www.automovileslucentum.com"),
(2,1,1,3,"207 SPORT 1. 4 VTI 16V 95CV",3800,2009,180000,"NEGRO",5,5,"Peugeot 207 SPORT 1. 4 VTI 16V 95CV. VEHÍCULO DISPONIBLE
 Muy buen estado, único propietario, llantas de aleación, sensor de lluvia y luminosidad, climatizador bizona, ordenador de a bordo, faros antiniebla delanteros, radio cd, volante de cuero, airbags delanteros laterales, anclajes isofix en plazas traseras, cadena de distribución, elevalunas eléctricos, retrovisores eléctricos, etc... Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. Visite nuestra web! www.automovileslucentum.com"),
(1,2,2,1,"Q7 3.0 tdi quattro sline",16000,2008,120000,"GRIS PLATA",5,5,"Audi Q7 3.0 tdi quattro sline. 
 Perfecto estado, único propietario, llantas de aleación 20, sensores de aparcamiento delanteros y traseros, faros bi-xenon, faros antiniebla, asientos con regulación eléctrica, volante multifunción de cuero regulable en altura y profundidad, climatizador bizona, radio cd con multicargador, navegador, regulador de velocidad, limitador de velocidad, suspensión neumática adaptable, sensor de lluvia y luminosidad, retrovisores eléctricos, caja automática tiptronic de 6 marchas, airbags laterales delanteros, ESP desconectable, tapicería de cuero, anclajes isofix en plazas traseras, 4 elevalunas eléctricos, acabado SLINE, etc...Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. Visite nuestra web! www.automovileslucentum.com"),
(6,2,1,1,"TOURAN 2.0 FSI 7 PLAZAS",5999,2005,80000,"NEGRO",5,7,"Volkswagen Touran 2.0 fsi 7 plazas. 
 Estado impecable, único dueño, 2 llaves, 7 plazas, tapicería de piel, retrovisores eléctricos, elevalunas eléctricos, control de velocidad, volante multifunción, cambio automático, ordenador de abordo, ESP desconectable, Radio CD, Climatizador bizona, sensores aparcamiento trasero, airbag de pasajero desconectable, faros de xenon, asientos calefactables, llantas de aleación, Reproductor DVD con pantalla LCD plazas traseras, reposabrazos central, luneta trasera calefactable, compartimentos portagafas, barras de techo... precio y equipación correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com."),
(13,2,2,1,"X5 XDRIVE 40D 3.0.",21900,2011,215000,"NEGRO",5,5,"VENDIDO
 Dos llaves, paquete M interior y exterior (acabado en piel, asientos con regulación eléctrica memorizable), llantas de aleación 20 pulgadas, neumáticos de doble medida, estriberas, barras de techo, transmisión automática (joystick), luces diurnas LED, faros Bi-xenon, faros antiniebla, sensor de lluvia y luminosidad, lunetas delantera y trasera calefactables, freno eléctrico, ordenador de a bordo, climatizador bizona, radio CD con cargador 6x, manos libres, volante multifunción de cuero, navegador, dirección eléctrica variable, control de tracción, ayuda en pendiente, velocidad de crucero, limitador de velocidad, asientos calefactables, retrovisores eléctricos antideslumbrantes, cristales de privacidad en plazas traseras, sistema llamada de emergencia, alarma, bola de remolque removible original, etc...precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com"),
(5,1,1,3,"FIESTA 1.2 82 CV",5499,2011,90000,"GRIS PLATA",5,5,"VEHÍCULO DISPONIBLE
En buen estado, dos llaves, llantas de aleación, faros antiniebla, volante multifunción, ordenador de a bordo, Radio CD, elevalunas eléctricos delanteros, Aire acondicionado, Airbags delanteros, Asiento conductor y volante regulables, Retrovisores eléctricos, anclajes Isofix en plazas traseras, etc... precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com"),
(4,1,1,3,"XSARA PICASSO 1.6",3600,2007,130000,"GRIS PLATA",5,5,"VEHÍCULO DISPONIBLE. En muy buen estado, único dueño, velocidad de crucero, limitador de velocidad, ordenador de abordo, cierre centralizado, elevalunas eléctricos, retrovisores eléctricos, airbags delanteros/laterales, climatizador, volante de cuero, banqueta trasera abatible 1/1/1/3, toma de 12v en plazas traseras, mesas plegables, etc...precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com"),
(17,2,2,3,"GRAND CHEROKEE OVERLAND",10499,2007,200000,"AZUL MARINO",5,5,"VEHÍCULO DISPONIBLE
 En perfecto estado, único dueño, motor 3.0 CRD con transmisión automática y 4x4 desconectable. llantas de aleación, faros antiniebla, sensores de aparcamiento delanteros y traseros, retrovisores antirreflejantes eléctricos, control de tracción, tapicería piel y alcántara, asientos calefactables con regulación eléctrica y memoria, volante multifunción de cuero con regulación eléctrica, velocidad de crucero, navegador, radio cd mp3, sonido Boston Premium, Climatizador bizona con salida en plazas traseras, elevalunas eléctricos, pedales con regulación eléctrica, dvd en plazas traseras, techo solar, etc... precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com"),
(9,1,2,1,"MEGANE LIMITED 1.5 110CV",7600,2014,100000,"BLANCO",5,5,"VEHICULO DISPONIBLE
En perfecto estado, único propietario, tarjeta de apertura y arranque manos libres, llantas de aleación Limited, luces de día LED, faros antiniebla, retrovisores eléctricos abatibles eléctricamente, ordenador de abordo, climatizador bizona, Radio CD MP3 Plug¬Radio bluetooth y manos libres, Volante de cuero multifunción regulable en altura y profundidad, asientos regulables, display digital, apoyabrazos central, freno de servicio eléctrico, velocidad de crucero y limitador de velocidad, control de tracción, sensor de lluvia y luminosidad, elevalunas eléctricos, sensores de aparcamiento traseros, sensores de presión de neumáticos, sensor de ángulo muerto, etc...precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com"),
(2,1,2,3,"307 SW 2.0 HDI 7 PLAZAS",3650,2004,160000,"BEIGE METALIZADO",5,7,"VEHÍCULO DISPONIBLE.
En muy buen estado, siete plazas, único dueño. Llantas de aleación, techo solar eléctrico, elevalunas eléctricos, cierre centralizado, retrovisores eléctricos y abatibles eléctricamente, volante de cuero, radio cd con multicargador para 5 discos y mandos en el volante, climatizador bizona, ESP desconectable, Airbags delanteros/laterales, lunas traseras tintadas, ordenador de abordo, dos apoyabrazos delanteros, bandejas abatibles en plazas traseras, etc... Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre.
visite nuestra web! www.automovileslucentum.com"),
(12,1,2,3,"SPORTAGE 2.0 CRDI EX",5999,2007,120000,"ROJO",5,5,"VEHÍCULO DISPONIBLE. 
En perfecto estado, motor 2.0 140cv, 4wd, llantas de aleación, faros antiniebla, barras de techo, retrovisores eléctricos, asientos regulables en altura, volante de cuero regulable en altura y profundidad, ordenador de a bordo, control de tracción, radio cd, climatizador, elevalunas eléctricos, airbags frontales/laterales, apoyabrazos central delantero y trasero, etc... Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. Visite nuestra web! www.automovileslucentum.com"),
(2,1,2,3,"PARTNER TOTEM 2.0 90CV",3999,2006,180000,"AZUL PIZARRA",5,5,"VEHÍCULO DISPONIBLE
 En muy buen estado, único propietario. Faros antiniebla, lunas tintadas, barras de techo, paquete SUV (protecciones guardabarros, faros delanteros y traseros) luneta trasera calefactable, radio cd mp3 con mandos en el volante y función manos libres, ordenador de a bordo, aire acondicionado, airbags frontales, cierre centralizado, elevalunas eléctricos, 2 reposabrazos, red de maletero, portón trasero, bola de remolque... Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. Visite nuestra web! www.automovileslucentum.com"),
(6,1,1,2,"POLO 1.4 ADVANCE 75CV",3999,2006,110000,"NEGRO",5,5,"vehículo disponible. 
En perfecto estado, único dueño, dos llaves. Retrovisores eléctricos, elevalunas eléctricos, luneta trasera calefactable, airbags laterales delanteros, radio cd mp3, aire acondicionado, cierre centralizado, etc...Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. Visite nuestra web! www.automovileslucentum.com"),
(4,1,1,2,"C2 VTS 1.6 16V 125CV",3999,2008,119000,"ROJO",3,4,"VEHÍCULO DISPONIBLE
En perfecto estado, único propietario, dos llaves, 4 plazas. Llantas de aleación 16 pulgadas, faros antiniebla delanteros, lunas tintadas de privacidad, retrovisores eléctricos, elevalunas eléctricos, radio cd mp3, volante de cuero regulable en altura, asientos regulables en altura, ordenador de a bordo, aire acondicionado, ESP desconectable, regulador de velocidad, airbags frontales/laterales, pedales de aluminio, acabado sport, cierre centralizado, etc...Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. Visite nuestra web! www.automovileslucentum.com"),
(4,1,2,1,"C3 1.4 HDI EXCLUSIVE",3999,2008,49000,"GRIS PLOMO",5,5,"VENDIDO
En perfecto estado, dos llaves. Faros antiniebla, retrovisores eléctricos abatibles eléctricamente, limitador de velocidad, velocidad de crucero, sensor de lluvia y luminosidad, climatizador, elevalunas eléctricos, volante y palanca de cambios en cuero, volante y asientos regulables, radio cd mp3 con mandos en el volante, Airbags frontales/laterales, anclajes isofix en plazas traseras, 2 reposabrazos, etc... precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www. automovileslucentum.com."),
(16,1,1,3,"URBAN CRUISER 1.3 2WD ACTIVE",8200,2010,90000,"BLANCO",5,5,"VEHÍCULO DISPONIBLE.
En perfecto estado, único propietario, dos llaves. Llantas de aleación, faros antiniebla, sensores de aparcamiento traseros, pasos de puerta de aluminio, elevalunas eléctricos, retrovisores eléctricos, Volante de cuero multifunción regulable, asientos regulables, modo ECO, control de tracción, navegador, reproductor de CD/DVD MP3 con mandos en el volante, climatizador, Airbags delanteros/laterales y de pasajero desconectable, ordenador de a bordo, etc... precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com"),
(2,1,1,2,"308 SW 1.6 VTi 120cv",5000,2008,115000,"ROJO",5,5,"VEHíCULO DISPONIBLE En muy buen estado, dos llaves, mando. Llantas de aleación, barras de techo cromadas, techo panorámico eléctrico, faros antiniebla, retrovisores eléctricos, CADENA DE DISTRIBUcIóN, ordenador de a bordo, radio cd mp3 con mandos en el volante, volante y palanca de cambios de cuero, asiento regulable, climatizador bi zona con ventilación en plazas traseras, anclajes isofix en plazas traseras, airbags delanteros/laterales, etc. . . precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com."),
(4,1,1,3,"C3 1.4 SX PLUS",5500,2010,95000,"GRIS PLATA",5,5,"VEHÍCULO DISPONIBLE. 
Impecable, único dueño, dos llaves. Faros antiniebla, retrovisores eléctricos, elevalunas eléctricos, ordenador de a bordo, climatizador automático, radio CD con mandos en el volante, volante de cuero regulable, asientos regulables, anclajes isofix en plazas traseras, airbags frontales/laterales, palanca de cambios en cuero, regulador de velocidad, entrada usb y 12v, etc... precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com"),
(16,1,1,2,"YARIS 1. 3 VVTI LUNA",3800,2006,80000,"GRIS PLATA",5,5,"VEHÍCULO DISPONIBLE
Impecable. Llantas de aleación, transmisión por cadena, asistencia frenada de emergencia, dirección asistida eléctrica, retrovisores eléctricos, elevalunas eléctricos, airbags delanteros/laterales (pasajero desconectable) volante de cuero multifunción y regulable, palanca de cambios en cuero, radio CD MP3, asiento regulable,anclajes isofix en plazas traseras, asientos toyota easy flat, etc... precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#. Visite nuestra web! www.automovileslucentum.com"),
(10,1,1,3,"ALTEA 1.4 TSI 125CV",7500,2010,90000,"BEIGE METALIZADO",5,5,"VEHÍCULO DISPONIBLE
En magnífico estado, dos llaves, único propietario, matriculado en noviembre de 2009. . Llantas de aleación, faros antiniebla, sensores traseros de aparcamiento, cadena de distribución, sensor de lluvia y luminosidad, elevalunas eléctricos, retrovisores eléctricos abatibles, control de tracción, regulador de velocidad, sensor de presión de neumáticos, volante de cuero multifunción y regulable, asientos regulables, radio CD con mandos en volante, palanca de cuero con 6 velocidades, climatizador bizona, función manos libres para smartphone con entrada USB, 2 entradas auxiliares 12v, asientos regulables, 6 airbags (pasajero desconectable), apoyabrazos central, anclajes isofix en plazas traseras, etc... Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre.
 visite nuestra web! www.automovileslucentum."),
(9,1,2,3,"SCENIC 1.5 DCI 105cv",2600,2005,220000,"GRIS PLATA",5,5,"VEHÍCULO DISPONIBLE. 
 En muy buen estado. Faros antiniebla, llantas de aleación, tarjeta de apertura y arranque, retrovisores eléctricos, elevalunas eléctricos, limitador de velocidad, control de velocidad de crucero, freno de estacionamiento eléctrico, sensor de lluvia y luminosidad, volante de cuero multifunción regulable, asientos regulables, palanca de cambio en cuero, aire acondicionado, radio CD con mandos en el volante, Airbags frontales/laterales, anclajes isofix y mesillas tipo avión en plazas traseras, etc...Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre."),
(4,1,2,2,"C4 PICASSO 1.6 HDI 110CV MILLENIUM",8500,2011,100000,"NEGRO",5,5,"VEHÍCULO RESERVADO
EN PERFECTO ESTADO. único propietario, dos llaves. Luces diurnas LED, faros antiniebla, llantas de aleación, sensores traseros de aparcamiento, retrovisores eléctricos abatibles, elevalunas eléctricos, sensor de lluvia y luminosidad, ESP desconectable, Radio CD MP3 Bluetooth con navegador, función manos libres para smartphone, volante de cuero multifunción regulable, asientos regulables, palanca de cuero 6 velocidades, freno de estacionamiento eléctrico, limitador de velocidad, regulador de velocidad crucero, climatizador bi-zona, 2 reposabrazos delanteros, anclajes isofix en plazas traseras, 6 airbags (pasajero desconectable), retrovisor de vigilancia de niños, lunas tintadas, etc. . . Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. visite nuestra web! www. automovileslucentum. com."),
(6,1,1,1,"GOLF IV 1.6 105 CV",2200,2002,150000,"NEGRO",5,5,"VEHíCULO DISPONIBLE En muy buen estado, único dueño, dos llaves, cubiertas Michelin, 5 puertas, radio cd mp3 con usb, aire acondicionado, dirección asistida, cierre centralizado, asientos regulables, repetidor de intermitente, palanca en cuero, itv al día, etc. . . Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. visite nuestra web! www. automovileslucentum. com"),
(10,1,2,3,"LEON 1.6TDI 105CV STYLE",7600,2011,70000,"GRIS ANTRACITA",5,5,"VEHÍCULO DISPONIBLE
 En perfecto estado, dos llaves, único propietario. Llantas de aleación 17 pulgadas, faros antiniebla, retrovisores eléctricos, luneta trasera calefactable, sensor de neumáticos, entrada usb, control de velocidad de crucero, limitador de velocidad, volante regulable multifunción, asientos regulables, palanca en cuero, radio CD, climatizador bizona, elevalunas eléctricos, función manos libres para smartphone, ordenador de a bordo, airbag de pasajero desconectable, anclajes isofix en plazas traseras, repetidores de intermitente, etc... Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. visite nuestra web! www.automovileslucentum.com"),
(7,1,1,3,"CORSA 1.2 111 YEARS 85CV",4999,2010,100000,"NEGRO",5,5,"VEHÍCULO DISPONIBLE
En perfecto estado, único dueño, dos llaves, faros antiniebla, llantas de aleación, retrovisores eléctricos, elevalunas eléctricos, volante de cuero multifunción regulable, control de velocidad de crucero, limitador de velocidad, aire acondicionado, radio CD MP3, luneta trasera calefactable, palanca en cuero, cierre centralizado, ordenador de a bordo, airbags frontales/laterales, anclajes isofix en plazas traseras, umbrales de puerta de aluminio, ABS, ESP, asientos regulables, repetidor de intermitente, ITV hasta 2020, etc... Precio y equipamiento válido salvo error tipográfico. se entrega con 12 meses de garantía. hay que sumarle al precio eur 120 por cambio de nombre. visite nuestra web! www.automovileslucentum.com"),
(12,1,2,3,"SORENTO 2.5 CRDI ACTIVE 170CV",8600,2009,95000,"GRIS PLATA",5,5,"VEHÍCULO DISPONIBLE.
En muy buen estado, único propietario, dos llaves y mando, faros antiniebla, llantas de aleación, barras de techo, retrovisores eléctricos, elevalunas eléctricos, función 4WD, volante de cuero regulable, asientos regulables, radio CD MP3 con Bluetooth, manos libres para smartphone, luneta trasera calefactable, climatizador automático bizona, reposabrazos central, Airbags delanteros, palanca en cuero, ordenador de a bordo, ESP, ABS, etc... precio y equipamiento correctos salvo error tipográfico. Se entrega el vehículo con 12 meses de garantía. Al precio hay que sumarle 120€ #por cambio de nombre#
Visite nuestra web! www.automovileslucentum.com");